#!/usr/bin/env sh

echo "Running pre-commit checks ⧗.⧗.⧗"

npx lint-staged

if [ $? -ne 0 ]; then
  echo "Lint-staged failed ❌"
  exit 1
fi

npm test

if [ $? -ne 0 ]; then
  echo "Unit tests failed ❌"
  exit 1
fi

echo "Pre-commit checks passed ✅"